version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/go-memcached-elen
    container_name: practice_memcached_app
    restart: always
    ports:
      - "8787:8787"
    tty: true
    depends_on:
      - memcached
    networks:
      - fullstack
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    tty: true
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge